### PR TITLE
added query_encode=True support in text_scorer method.

### PR DESCRIPTION
**Pull request by hammadkhann**

### CODE REVIEW

**Comment by hammadkhann** [comment]
Maybe the Indexing test case is failing while building the project. @cmacdonald Can you please check?

**Comment by cmacdonald** [comment]
The pytorch version checking code was faulty, and incorrectly detection pytorch 1.10.0 as being not greater than 1.6.0. I am trying to fix it now.

**Comment by cmacdonald** [comment]
Ok, now error is in your court:
https://github.com/terrierteam/pyterrier_colbert/runs/4069242417?check_suite_focus=true#step:6:760

**Comment by cmacdonald** [comment]
Back to you:
https://github.com/terrierteam/pyterrier_colbert/runs/4070930227?check_suite_focus=true

I think you should be able to test it on the commandline, using pytest, before committing? I had to fix some syntax errors.

**Comment by cmacdonald** [comment]
Thanks Hammad

**Pull request merged**
